### ISSUE TITLE
where are the deblur test files installed

### ISSUE THREAD

**Issue by amnona** [biocore/deblur#105]
they are not in:
~/anaconda/envs/testdeb/lib/python3.5/site-packages/deblur/test/

**Comment by josenavas** [comment]
I think [these lines](https://github.com/biocore/deblur/blob/master/setup.py#L44) are wrong? I think they should be a slash rather than a dot.

**Comment by wasade** [comment]
Is this still an issue? Is there a reason to graft the test files for an install?

**Comment by wasade** [comment]
Unclear if this is still an issue or the need for the test files on to carry with a deploy
