### ISSUE TITLE
problem with scikit-bio on mac

### ISSUE THREAD

**Issue by amnona** [biocore/deblur#126]
users get:
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ

* i think it is coming from scikit-bio on mac (this is what imports matplotlib)

to solve need to do:
cd ~/.matplotlib 
 echo "backend: TkAgg" >> ~/.matplotlib/matplotlibrc

maybe add to doc?

**Comment by wasade** [comment]
I think it would make sense to note this as in a "troubleshooting" section on the readme.
