### ISSUE TITLE
doc string for negate is inaccurate

### ISSUE THREAD

**Issue by wasade** [biocore/deblur#127]
[`--ref-db`](https://github.com/biocore/deblur/blob/master/scripts/deblur#L483) does not exist for `workflow`

**Comment by wasade** [comment]
This is still an issue. @amnona, for example, this part of the [help](https://github.com/biocore/deblur/blob/master/scripts/deblur#L206) string refers to an option which does not exist for the associated command.

**Comment by amnona** [comment]
I think it is ok.
We still have the --negate flag in the remove_artifacts command (as opposed to workflow command). And the --pos-ref-fp and -neg-ref-fp flags do exist (with the names of the positive and negative fasta files). When you just run remove_artifacts, you can choose if you want to remove the positive or the negative.

**Comment by wasade** [comment]
It is not okay for help text to refer to an option that does not exist

**Comment by amnona** [comment]
right, in the remove_artifacts we use only the --ref-fp option since we supply only one database... fixed.
