### ISSUE TITLE
--min-reads default is zero

### ISSUE THREAD

**Issue by wasade** [biocore/deblur#128]
...however, we use a value of 10 with qiita which was also the value used for the AG comparisons in the manuscript. Should this default be back propagated to deblur proper?

**Comment by josenavas** [comment]
Actually, can this filtering be done after the fact using QIIME scripts? If so I would suggest leaving the current value (0) as default in Qiita.

**Comment by wasade** [comment]
qiita is using 10 according to the processing parameters I'm seeing for the 3 deblur runs on study 2136.

**Comment by josenavas** [comment]
Thanks for looking into it @wasade 

if that is the recommended behavior for deblur, then I think it is ok to propagate back to deblur.

**Comment by wasade** [comment]
Resolved in #130
