### ISSUE TITLE
artifacts.fa is not correctly formatted

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/deblur#129]
This file is referenced in the readme to use with negative filtering, but there is at least one missing line break that causes it to not be valid fasta.

**Comment by amnona** [comment]
i don't see/understand the problem. Any ideas?

**Comment by gregcaporaso** [comment]
See [here](https://github.com/biocore/deblur/blob/master/deblur/support_files/artifacts.fa#L156).

**Comment by amnona** [comment]
fixed. thanks :)
