### ISSUE TITLE
I've got my deblurred sequences. How do I run diversity analyses on the biom file?

### ISSUE THREAD

**Issue by slvrshot** [biocore/deblur#143]
I tried running the core_diversity_analyses.py script in qiime using the deblurred sequences but it said something about I didn't have metadata in my biom file. When I added the metadata it still didn't seem to like my .biom file so I was not sure what to do. Is there a suggested workflow for visualizing the deblurred sequence data? In qiime I normally just run the open_reference worklow at 97% similarity followed by core diversity analyses using an even sample depth....and using the rarefied output in phyloseq. Please help! Thanks

**Comment by slvrshot** [comment]
I converted the otu table and noticed that the taxonomy for each sample is a sequence. This is very curious but it makes sense we are not clustering sequences with OTUs. Still I would like to know what exactly am I supposed to do with the table?

**Comment by wasade** [comment]
@slvrshot, `Deblur` is analogous to one of the OTU picking pipelines in QIIME, and in general, any method in QIIME which accepts a BIOM table will accept one produced by Deblur (e.g., `beta_diversity.py`, `single_rarefaction.py`, etc). The output from Deblur does not assign taxonomy, and it needs to be added in separately as can be done with `assign_taxonomy.py`. 

I'm closing this issue as it appear to be centered around interoperability with QIIME which would be more appropriate on the qiime-forum.

**Comment by slvrshot** [comment]
Maybe I did not properly ask the question. How do I convert or change the observation ids which contain deblurred sequences )mine are 350 bp) to taxa?

**Comment by wasade** [comment]
@slvrshot, taxonomy assignment is out-of-scope for Deblur itself. If you're using QIIME2, then I recommend using `q2-feature-classifier` (an example is [here](https://docs.qiime2.org/2017.2/tutorials/moving-pictures/#taxonomic-analysis)), and which can consume the outputs of the `q2-deblur` [plugin](https://github.com/wasade/q2-deblur). If you're using QIIME1, then I recommend using `assign_taxonomy.py` which in turn uses the RDP Classifier, and which can consume the sequence file output from Deblur. I'm not familiar enough with tools like mothur to know what steps are necessary there.
