### ISSUE TITLE
Deblur outputs lowercase characters

### ISSUE THREAD

**Issue by mortonjt** [biocore/deblur#148]
Here is an example of deblurred sequence
```
>AACggggggggCAAGTGTTCTTCGGAATGACTAGGCGTAAAGGGCACGTAGGCGGTTCATCGGGTTGAAAGTGAAAGTCGTCAAAAAGTG
AACggggggggCAAGTGTTCTTCGGAATGACTAGGCGTAAAGGGCACGTAGGCGGTTCATCGGGTTGAAAGTGAAAGTCGTCAAAAAGTG
```
Is there a reason why this gets outputted?  This can cause problems downstream, since q2-feature-classifier cannot handle lowercase characters.

**Comment by mortonjt** [comment]
ping on this issue - this is a serious user issue, because it is a major technical barrier when trying to perform taxonomic classification.  Otherwise the user will be forced to be running
`tr '[:lower:]' '[:upper:]'`

At the very least, we need to document this.

**Comment by ElDeveloper** [comment]
I too have encountered this problem, however I assumed this was a sequencing artifact (low quality NTs). There's an issue for this in q2-types https://github.com/qiime2/q2-types/issues/91 That being said, if deblur is changing NTs to lowercase, what is the rationale for that?

Yoshiki Vázquez-Baeza

**Comment by wasade** [comment]
It's stemming from MAFFT iirc. I'd be :+1: for a PR to coerce to all upper
case

**Comment by jakereps** [comment]
Just stumbled across this through the `q2-types` issue. One thing QIIME 2 does (in `q2_alignment.methods.mafft`) is pass `--preservecase` to MAFFT, which may be an option for this as well by adding it to [here](https://github.com/biocore/deblur/blob/afba6a195bf6eb2c249bccffc3a842da64fdfaca/deblur/workflow.py#L519-L520).

**Comment by wasade** [comment]
Which q2types issue?

**Comment by jakereps** [comment]
The importing issue that Yoshiki mentioned, about QIIME 2 being unable to import lowercase sequences. I just ran into an issue with that by running MAFFT external to q2, and since he tagged it here this issue showed up on that page.

**Comment by wasade** [comment]
Ah, kk

**Comment by ElDeveloper** [comment]
Any way this can be included in a release soon?
