### ISSUE TITLE
Errors: IndexError: index returns 3-dim structure and ERROR: `3` is not supported in --blast [STRING].

### ISSUE THREAD

**Issue by smteo** [biocore/deblur#150]
Hi,

I'm trying Deblur for the first time and ran the following command:
deblur workflow --seqs-fp seqs.fna --output-dir deblur_test -t 240 --min-reads 1 --min-size 1 --keep-tmp-files --log-level 1

It returned with an error:
 File "/usr/local/easybuild/software/Python/3.5.2-vlsci_intel-2015.08.25/lib/python3.5/site-packages/scipy/sparse/sputils.py", line 344, in _index_to_arrays
    raise IndexError('index returns 3-dim structure')
IndexError: index returns 3-dim structure

When I look in the log file the are these errors:
ERROR(47590929782720)2017-05-02 12:54:32,325:sortmerna error on file /vlsci/SG0006/shared/COAST_16S/AGRF_CAGRF13540_002/flash_output/split_lib_output/deblur_tes
t/deblur_working_dir/53_AULMM_AATCAGTCTCGT_L001_.extendedFrags.fastq.fasta.trim.derep
ERROR(47590929782720)2017-05-02 12:54:32,325:stdout : 
ERROR(47590929782720)2017-05-02 12:54:32,325:stderr : 
  ERROR: `3` is not supported in --blast [STRING].

**Comment by amnona** [comment]
It seems maybe you have the wrong sortmerna version installed in the deblur conda environment?
Can you source activate the deblur environment and type:
sortmerna --version
It should be 
SortMeRNA version 2.0, 29/11/2014

**Comment by smteo** [comment]
My version now is 2.1. I will install 2.0 and try again. Thank you.

**Comment by wasade** [comment]
@smteo, is this still an issue? Please reopen if necessary.
