### ISSUE TITLE
possible to upgrade mafft dependency to 7.310?

### ISSUE THREAD

**Issue by jairideout** [biocore/deblur#152]
Is it possible to upgrade deblur's mafft dependency to version 7.310? Right now the conda recipe [requires version 7.221](https://github.com/biocore/conda-recipes/blob/master/recipes/deblur/meta.yaml#L31). We [discovered a bug](https://github.com/qiime2/q2-alignment/issues/34) in mafft versions prior to 7.310 that impacts QIIME 2's q2-alignment plugin (the issue could also affect deblur users, it isn't specific to QIIME 2). Thanks!

**Comment by wasade** [comment]
The bug is on an improper exit status from OOM, not results? The OOM would be extremely pathological for Deblur's use especially given it hasn't popped up even with Yatsunenko et al 2012. Changing versions of mafft is not trivial unfortunately, and I'm not sure who has bandwidth for it near term.

Bumping the dependency to resolve an exit status issue is a short term solution for qiime2 though. It is not uncommon for tools in the bioinformatics space to return 0 when they fail. IIRC, this was one of the joys of Galaxy that they had to work around.

**Comment by wasade** [comment]
Thanks @ElDeveloper for kicking Travis.

@jairideout, my apologies, I could have sworn the results were unstable relative to the MAFFT version, but @ElDeveloper's test suggests otherwise. Before merge of #153, I'd like to verify `q2-deblur` as well

**Comment by jairideout** [comment]
Great, thanks for working on updating deblur's MAFFT @wasade and @ElDeveloper! Let me know if I can help out with testing on the QIIME 2 side of things.

> The bug is on an improper exit status from OOM, not results?

It can happen with OOM, but I can also trigger the bug by killing the process at any point during MAFFT's execution (e.g. by hitting Ctrl-C or `kill 9`). The bug triggers if MAFFT's child process dies in any way. Let me know if that doesn't answer your question!

> Bumping the dependency to resolve an exit status issue is a short term solution for qiime2 though. It is not uncommon for tools in the bioinformatics space to return 0 when they fail. IIRC, this was one of the joys of Galaxy that they had to work around.

This is the first time we've encountered an exit code issue, and it ended up being a bug on MAFFT's end (which the MAFFT devs fixed). If there are other tools that don't use exit codes properly, we'll deal with them when they're added to the QIIME 2 ecosystem. If you know of any existing qiime2 dependencies that behave this way, can you create issue(s) so we can investigate? That'd be a huge help!

**Comment by wasade** [comment]
Don't know off hand but the RNA apps from cogent were a mixed bag.

**Comment by wasade** [comment]
Fixed in #153

**Comment by jairideout** [comment]
Thanks @wasade! Is there a new conda build of Deblur that we can start testing?

**Comment by wasade** [comment]
We have not tagged a new release yet. Can you operate off master?

**Comment by jairideout** [comment]
No, our build system looks for dependencies in a predefined set of conda channels.
