### ISSUE TITLE
update required vsearch version

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/deblur#158]
The vsearch version that is currently required (2.0.3) has [a bug](https://github.com/torognes/vsearch/issues/201) that is [preventing some functionality from being added to the `q2-vsearch` plugin](https://github.com/qiime2/q2-vsearch/issues/24). It would be helpful if deblur could use a more recent version of vsearch. The vsearch bug was reported to have been fixed in 2.1.1. (I don't think this vsearch bug impacts deblur.)

**Comment by ElDeveloper** [comment]
Closed in #159 though I believe the conda recipe will need to be updated (after a new release is published).

**Comment by wasade** [comment]
@ElDeveloper, can this issue be closed?

**Comment by ElDeveloper** [comment]
I think so.
