### ISSUE TITLE
Getting the output and summary of the artifact filtering

### ISSUE THREAD

**Issue by amnona** [biocore/deblur#2]
Yay, i'm writing an issue on github :)
1. When running the HMMER (or the phix detection) artifact filtering, we should output a summary of how many sequences were filtered out
2. Also add a flag/option to get a file with all the filtered out sequences (to see who they are...)

**Comment by RNAer** [comment]
The second one is a debug flag to save all (necessary) intermediate files

**Comment by amnona** [comment]
1. in the log file
2. have it in the -n mode
