### ISSUE TITLE
Use thread id instead of exposing a parameter to the user

### ISSUE THREAD

**Issue by josenavas** [biocore/deblur#36]
See original discussion [here](https://github.com/biocore/deblur/pull/35#discussion_r71966934)

**Comment by wasade** [comment]
It looks like the process rank can be determined with `multiprocessing.current_process()`. While I agree this is better, and agree that the current flag can confuse users, I don't believe this is blocking. And while the flag might be confusing, it is currently denoted in the help text as not to be used by users.

**Comment by josenavas** [comment]
Agree re not blocking, however I think we should leave the issue open to fix later.

**Comment by wasade** [comment]
This doesn't seem to be in issue or confusing in practice, so closing
