### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by mortonjt** [biocore/deblur#38]
Its not clear exactly what dependencies are required to run this.

After talking to @josenavas, I realized that MAFFT and SortMeRNA are required.
What other dependencies are required?  The documentation will need to be updated with this information, so we can turn this into a conda recipe.

**Comment by josenavas** [comment]
The required dependencies are vsearch, sortmerna, mafft.

👍 for the conda recipe

**Comment by amnona** [comment]
cool :)
Thanks!

**Comment by wasade** [comment]
@mortonjt, I believe this can be closed out now? The `readme.md` notes the biocore dependencies
