### ISSUE TITLE
update deblur workflow defaults

### ISSUE THREAD

**Issue by amnona** [biocore/deblur#44]
need to set:
- [x] read length?
- [x] error profile
- [x] positive or negative filtering
- [x] fasta file for negative filtering
- [x] indexed 88_otus.fasta or the 88_otus.fasta for positive filtering

**Comment by wasade** [comment]
@amnona, I assigned you to this as I believe you're best to resolve. I also updated the issue with fancy check boxes so they can be knocked off as they complete :)

**Comment by amnona** [comment]
all set :)
