### ISSUE TITLE
Documentation bits for release

### ISSUE THREAD

**Issue by wasade** [biocore/deblur#48]
- [x] example install via pip or conda
- [x] basic command shown should reflect the click command structure
- [x] add change log

**Comment by wasade** [comment]
Partially addressed in #58

**Comment by wasade** [comment]
@mortonjt, since deblur is in the biocore conda recipes, and since its build has a rational dependency chain, isn't it the case that the install example in the readme (currently `conda install -c biocore VSEARCH MAFFT SortMeRNA numpy`) can be changed to (`conda install -c biocore deblur`)?

**Comment by mortonjt** [comment]
Exactly :)
