### ISSUE TITLE
pip installable

### ISSUE THREAD

**Issue by wasade** [biocore/deblur#50]

**Comment by wasade** [comment]
I'm going to just do pip for now instead of conda because it's easier out of the box. Once we knock out version 1.0 tickets, we can cut a release and upload.

**Comment by mortonjt** [comment]
Are you sure?  You can't install MAFFT/SortMeRNA/Vsearch from pip can you?

**Comment by wasade** [comment]
No real preference. Readme states whats needed to get those deps. But going
from 2 commands down to 1 is preferrable

**Comment by wasade** [comment]
@mortonjt, can I assign this to you for setting this up in conda? Please remember:

- [ ] update readme for install

**Comment by mortonjt** [comment]
Sounds good

**Comment by mortonjt** [comment]
Might not need pip - the conda recipe is compiling

https://github.com/biocore/conda-recipes/pull/64

**Comment by wasade** [comment]
@mortonjt, this can be closed, right?

We'll still need to push up the latest greatest to conda once the milestone is cleared out...

**Comment by mortonjt** [comment]
Closed by https://github.com/biocore/conda-recipes/pull/64
