### ISSUE TITLE
saving to json (when h5py isn't present) doesn't actually work

### ISSUE THREAD

**Issue by wasade** [biocore/deblur#51]
Strongly recommend removing biom 1.x format support and requiring h5py.

**Comment by ElDeveloper** [comment]
@mcdonadt, why? In QIIME we allow for both formats and I haven't seen any trouble with that.

Yoshiki Vázquez-Baeza

**Comment by wasade** [comment]
QIIME writes them out correctly

**Comment by wasade** [comment]
What's the benefit of supporting both? H5py is trivial to install with
conda and pip

**Comment by amnona** [comment]
Some people like to work with txt tables (in r/stass/excel etc.)
and i personally know someone who had trouble installing hdf5 on their
server :)
I think leaving the option to save as text does not cost us much, and may
help other people...
(and if it is not working - i'll try to make it work)

**Comment by wasade** [comment]
Excel doesn't read json as far as I know

I don't see why it is important to carry maintenance and development burden
in order to support the < 0.1% case which can be handled with normal user
support

**Comment by wasade** [comment]
Can keep but please verify functionality. Tests were not passing until h5py
was present

**Comment by ElDeveloper** [comment]
Mainly convenience (installation of hdf5/h5py), the biom-format package
already supports both formats, so the burden for this package is
minimal.

**Comment by wasade** [comment]
Makes it more difficult to kill off old formats though.

**Comment by wasade** [comment]
Any issues here are alleviated by adding `h5py` to `conda_requirements.txt`. Can we do that and drop 1.0.0 support?

**Comment by mortonjt** [comment]
Yeah - now that hdf5 and h5py are conda installable, this shouldn't be an issue.  I'm down for dropping the old formats, considering that converting between them isn't too bad.

**Comment by ElDeveloper** [comment]
If the plan is to stop supporting the JSON-based format at some point,
then this makes sense.

**Comment by wasade** [comment]
That is my hope, and it won't die if biocore continues to foster its use.

Current plan with q2 is support reading in order to handle legacy q1 data, but writing will be biom-format 2.1. The JSON representation hasn't scaled to the sized datasets in use for a few years now. If you haven't looked at `biom.Table.to/from_json`, I encourage you to take a peak at the terrible things done there in order to allow that representation to scale. (although, in general the biom io subsystem sucks but the larger effort is on delay for skbio)

**Comment by ElDeveloper** [comment]
OK, in that case it makes sense to drop support for 1.0, 👍

**Comment by amnona** [comment]
Agree about removing json
How about writing to .txt if no hdf5?
(We should also add the .txt output option as a flag for users who like to
parse txt table....)

**Comment by mortonjt** [comment]
That isn't critical, since that is already handled by biom explicitly out
of the box

http://biom-format.org/documentation/biom_conversion.html

If necessary, we could add docs to the README to alert users how to convert
their biom tables to text files.

**Comment by wasade** [comment]
we can just require h5py then we don't have an issue of hdf5 not being
present
