### ISSUE TITLE
explain run deblur after split_libraries_fastq

### ISSUE THREAD

**Issue by amnona** [biocore/deblur#54]

**Comment by wasade** [comment]
@amnona, just to check, does this mean showing an example going from QIIME's `split_libraries_fastq.py` to using `deblur`?

**Comment by amnona** [comment]
don't think that's needed
just need to explain deblurring needs to be run on a directory of per-sample fasta files, or alternatively on the seqs.fna output file of qiime split_libraries_fastq.py (demultiplexed fasta file <- with a link detailing the format in qiime)?

**Comment by wasade** [comment]
Okay, so this issue surrounds a more comprehensive example than the one in `README.md`
