### ISSUE TITLE
python 2.7 compatability

### ISSUE THREAD

**Issue by amnona** [biocore/deblur#56]
just need to change the one import for stringio to include if version

**Comment by wasade** [comment]
Since QIIME2 and scikit-bio are Py3 only, what is the benefit of furthering support for legacy python on new projects?

**Comment by wasade** [comment]
Also, it blocks use of newer versions of scikit-bio

**Comment by mortonjt** [comment]
The argument was that python2.7 users could still use deblurring in their environments.

However, I agree.  These days, its so easy to just build a new PY3 environment with all of the proper deblur dependencies.  👍 for PY3 compatibility only.

**Comment by wasade** [comment]
So are we good for closing this and py27 support?

**Comment by wasade** [comment]
@amnona, you on board with this?

**Comment by amnona** [comment]
sure.
if we use scikit bio which is py3 dependent, no use in supporting py27 :)

**Comment by wasade** [comment]
excellent point :)

**Comment by wasade** [comment]
Closing as we are not supporting py27
