### ISSUE TITLE
Use lookup table for translate the sequence to np array

### ISSUE THREAD

**Issue by josenavas** [biocore/deblur#6]
See [here](https://github.com/biocore/scikit-bio/pull/53#discussion-diff-9171472)

**Comment by wasade** [comment]
Note, it is essentially the same as using a lookup array in C. The
advantage is that all lookups are O(1) as it is indexing into an array.
Hashing is O(1) as well, except the hash computation is an appreciable
difference. Additionally, you can likely do bulk numpy ops which tend to be
faster than pure Python

**Comment by wasade** [comment]
Currently performance of the code is pretty good. This might be useful to do in the future, but I think we should table it for now.
