### ISSUE TITLE
sortmerna 2.1 changes cli

### ISSUE THREAD

**Issue by amnona** [biocore/deblur#60]
following @ekopylova  response, need to use sortmerna v2.1 and update the cli call inside workflow

**Comment by amnona** [comment]
biocore currently has only sortmerna 2.0 for mac
bioconda does not have sortmerna for mac
however, bioconda has sortmerna 2.1 for unix
need to decide how to work (the --blast api is expected to be stable following 2.1)

**Comment by wasade** [comment]
Possible to update the recipe for bioconda?

**Comment by mortonjt** [comment]
That's what we'll have to do.  Note that we don't need to do this for
version 1.0 of deblur

**Comment by wasade** [comment]
Okay, thanks. So @mortonjt can this be switched to milestone 2.0?

**Comment by wasade** [comment]
This seems like it'd be rather simple as it's just updating conda channels, and those need to be updated anyway (if not already) for sortmerna. Additionally, it also looks like sortmerna 2.1 is already in bioconda for [osx and linux](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/sortmerna/2.1b/meta.yaml), so is this actually still an issue?

**Comment by amnona** [comment]
the problem is that sortmerna 2.1 changed the blast output format. so we need to change deblur to read the new format (for the pos/neg filtering) instead of the sortmerna 2.0 format. Verified with Jenya. She also said it's not critical to update to 2.1.
So if we want deblur to use sortmerna2.1 we need to change the deblur program itself. I think we should stick with the tested 2.0?

**Comment by wasade** [comment]
okay

**Comment by wasade** [comment]
No clear reason why sortmerna 2.1 should be used, closing.
