### ISSUE TITLE
access supplied positive and negative data files by default

### ISSUE THREAD

**Issue by amnona** [biocore/deblur#61]
positive (gg 88% rep set) and negative (phix+adapter) fasta files are a part of the git
need deblurring to access them by default based on the mode (-n)
also need to test if not indexed, index them (1st time or as part of the install) and then use the indexed versions by default to save re-indexing each run...

**Comment by amnona** [comment]
Added the default data files. need to address indexing (on first run/on install)

**Comment by mortonjt** [comment]
Can you raise a separate issue for that?

**Comment by mortonjt** [comment]
Addressed by https://github.com/biocore/deblur/pull/62
