### ISSUE TITLE
cropped taxonomy strings

### ISSUE THREAD

**Issue by mortonjt** [biocore/deblur#64]
Looking at some of the taxonomy metadata, the last few characters are cropped off.  Here is an example of such a taxonomy string.

```
['k__Bacteria',  'p__Proteobacteria',  'c__Alphaproteobacteria',  'o__Sphingomonadales', 'f__Sphingomonadaceae']
```

Notice how the last few items are cropped off (i.e. genus and species).  This makes it more difficult to load the taxonomies into a pandas dataframe.

It would be great if some padding could be done in the post processing.

**Comment by wasade** [comment]
Context? Is this after running deblur?

**Comment by mortonjt** [comment]
Right, this from the resulting deblurred table after assigning taxonomy.

**Comment by wasade** [comment]
But deblur doesn't assign taxonomy unless I'm confused about something

**Comment by mortonjt** [comment]
Just talked to @amnona offline.  This is was generated using qiime's assign taxonomy.  So this is not relevant to deblurring.
