### ISSUE TITLE
sortmerna problem from biocore

### ISSUE THREAD

**Issue by amnona** [biocore/deblur#80]
sortmerna does not run on barnacle when obtained from biocore
it needs glibc 2.16
one workaround is to change to install instructions to use bioconda instead

**Comment by ElDeveloper** [comment]
If we can move to use conda-forge, glibc problems will disappear.

**Comment by josenavas** [comment]
@ElDeveloper do you have instructions on how to do it or can assist @ekopylova and @amnona to get it into conda-forge?

**Comment by ElDeveloper** [comment]
Yes! If we can meet for a bit I'm sure we can plow through this. Plus we get Windows builds 🎉

**Comment by amnona** [comment]
cool. thanks!
BTW: encountered same problem for vsearch (and probably MAFFT but didn't
check...)

**Comment by wasade** [comment]
This would be great. Updates to libc across broad infrastructure is a pain

**Comment by wasade** [comment]
I do not believe this is still an issue. Please reopen if necessary
