### ISSUE TITLE
add positive and negative reference db flags

### ISSUE THREAD

**Issue by amnona** [biocore/deblur#88]
so we can have a non-default pos database for the post-deblur positive filtering

**Comment by mortonjt** [comment]
looks like this is addressed. Close?

**Comment by josenavas** [comment]
No, we need 2 different flags to pass the different references.

**Comment by mortonjt** [comment]
I'm pretty sure that we addressed this in #87 .  There are 4 new parameters introduced `--neg-ref-fp`, `--neg-ref-fp-db` `--pos-ref-fp`, `--pos-ref-fp-db`.  on lines 415 - 446.  @amnona can you confirm this?

**Comment by josenavas** [comment]
You're right - @amnona please add `Fix #XX` to your PR to automatically close issues when code is merged.

**Comment by amnona** [comment]
good to know :) Thanks.
