### ISSUE TITLE
Trim flags are documented incorrectly

### ISSUE THREAD

**Issue by cuttlefishh** [biocore/deblur#91]
Using gibhub version of Deblur as of ~Oct 12, there are several inconsistencies with documentation:
- `--help` says `--trim` is the option to set trim length (I'm assuming this is the `-t` mentioned in README.md), but using `--trim` generates an error saying there is no such option and did I mean `--trim-length`.
- README.md says `-t` trims to 150bp by default but I am seeing behavior trimming to 100bp.

**Comment by tanaes** [comment]
Yup, default trim length in code is 100: https://github.com/biocore/deblur/blob/e0eed958c48a5ce6954c978c5e03ff3a3e4c96d7/scripts/deblur#L122

**Comment by wasade** [comment]
I believe this is resolved with #130, please reopen if necessary
